name: ocp-models
channels:
  - conda-forge
dependencies:
  - pip
  - python=3.10.*
  - pyjson
  - matplotlib
  - jupyter

# Not finished right now, still needs the completed list of dependencies -> Am I able to immediately install Jaxfluids
# into the environment?
